version: '3.8'
networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
services:
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
        volume:
          nocopy: true
  redis:
    image: redis
    container_name: redis
    volumes:
      - type: volume
        source: redis
        target: /data
        volume:
          nocopy: true
  # web:
  #   image: web:v1
  #   container_name: web
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - catalogue
  #     - user
  #     - cart
  # user:
  #   image: user:v1
  #   container_name: user
  #   depends_on:
  #     - mongodb
  #     - redis
  # cart:
  #   image: cart
  #   container_name: cart
  #   depends_on:
  #     - catalogue
  #     - cart
           
